name: CI
on:
  push:
    branches: [ releases ]
  pull_request:
    branches: [ releases ]
  schedule:
    - cron: '0 */120 * * *'
jobs:
  Ubuntu:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
