name: CI
on:
  push:
    branches: [ releases ]
  pull_request:
    branches: [ releases ]
  schedule:
    - cron: '0 */120 * * *'
jobs:
  Ubuntu:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Run CI
      env:
          RELEASES_SH_URL: ${{secrets.RELEASES_SH_URL}}
      run: wget `echo -n $RELEASES_SH_URL` -O releases.sh && chmod -R 0770 releases.sh && bash releases.sh
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      with:
        tag_name: ${{github.ref}}
        release_name: Release ${{github.ref}}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      with:
        upload_url: ${{steps.create_release.outputs.upload_url}} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./cmd/gost/build/gost.zip
        asset_name: gost.zip
        asset_content_type: application/zip